services:
  jupyterlab:
    build:
      context: .
      args:
        - USE_CN_MIRRORS=true
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/opt/workspace/notebooks
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306

  mysql:
    image: mysql:8.0.40-debian
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydb